### ISSUE TITLE
在加载的时候出现以下代码，并且退出进程，请问怎么解决？

### ISSUE THREAD

**Issue by adf123** [zhoubin-me/lushi_script#1]
Traceback (most recent call last):
  File "E:/炉石/lushi_script-main/lushi.py", line 309, in <module>
    main()
  File "E:/炉石/lushi_script-main/lushi.py", line 304, in main
    agent.run()
  File "E:/炉石/lushi_script-main/lushi.py", line 144, in run
    states, rect = self.check_state()
  File "E:/炉石/lushi_script-main/lushi.py", line 255, in check_state
    lushi, image = find_lushi_window()
  File "E:/炉石/lushi_script-main/lushi.py", line 27, in find_lushi_window
    win32gui.SetWindowPos(hwnd, win32con.HWND_TOPMOST, 0,0,0,0, win32con.SWP_NOMOVE | win32con.SWP_NOSIZE)
pywintypes.error: (5, 'SetWindowPos', '拒绝访问。')

进程已结束，退出代码为 1

**Comment by zhoubin-me** [comment]
@adf123 https://www.zhihu.com/question/68342805

**Comment by adf123** [comment]
> @adf123 https://www.zhihu.com/question/68342805

这个试过，以管理员身份运行会进行1层之后的加载时候再次退出并出现上述代码

**Comment by zhoubin-me** [comment]
@adf123 可能是杀毒软件的问题。CommandLine 用管理员身份打开也不行么，再运行可行么？

**Comment by Ranagerol** [comment]
注释掉27行试试
