### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mahone-mao** [zhoubin-me/lushi_script#100]
Traceback (most recent call last):
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 381, in <module>
    main()
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 377, in main
    agent.run()
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 330, in run
    self.run_pve()
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 366, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 258, in state_handler
    self.select_members()
  File "D:\tool\lushi_script\0.3.0\lushi.py", line 146, in select_members
    game = self.log_util.parse_game()
  File "D:\tool\lushi_script\0.3.0\log_util\log_util.py", line 29, in parse_game
    self.read_log()
  File "D:\tool\lushi_script\0.3.0\log_util\log_util.py", line 20, in read_log
    self.parser.read(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\hslog\parser.py", line 1100, in read
    self.read_line(line)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\hslog\parser.py", line 1135, in read_line
    return callback(self._parsing_state, ts, msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\hslog\parser.py", line 278, in handle_data
    ps.register_player(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\hslog\parser.py", line 140, in register_player
    lazy_player = self.manager.create_or_update_player(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\hslog\player.py", line 219, in create_or_update_player
    raise InconsistentEntityIdError(player, entity_id)
hslog.player.InconsistentEntityIdError: (PlayerReference(name='xxx', entity_id=4, player_id=3), 8)

**Comment by Huangyan0804** [comment]
删除powerlog日志并重启游戏

**Comment by zhujingpeng123** [comment]
2022-03-27 20:59:49,620 [   INFO] 2212 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 20:59:52,569 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-27 20:59:57,200 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 5.14
2022-03-27 21:00:02,097 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 10.04
2022-03-27 21:03:47,605 [   INFO] 10088 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:03:50,374 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:03:55,058 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 5.20
2022-03-27 21:03:59,768 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 9.91
2022-03-27 21:04:04,395 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 14.54
2022-03-27 21:04:09,063 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 19.21
2022-03-27 21:04:13,938 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 24.08
2022-03-27 21:04:18,543 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 28.69
2022-03-27 21:04:23,240 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 33.38
2022-03-27 21:04:28,179 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 38.32
2022-03-27 21:04:32,961 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 43.10
2022-03-27 21:04:37,539 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 47.68
2022-03-27 21:04:42,165 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 52.31
2022-03-27 21:04:47,042 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 57.18
2022-03-27 21:04:51,750 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 61.89
2022-03-27 21:04:56,557 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 66.70
2022-03-27 21:05:35,185 [   INFO] 2464 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:05:37,944 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 0.53
2022-03-27 21:05:42,684 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 5.27
2022-03-27 21:05:47,288 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 9.87
2022-03-27 21:05:51,988 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 14.57
2022-03-27 21:08:20,832 [   INFO] 5544 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:08:23,647 [   INFO] 5544 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:08:28,282 [   INFO] 5544 --- lushi.py:896  : Last state , time taken: 5.15
2022-03-27 21:08:51,641 [   INFO] 5616 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:08:54,429 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 0.54
2022-03-27 21:08:59,058 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 5.17
2022-03-27 21:09:03,609 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 9.72
2022-03-27 21:09:08,092 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 14.20
2022-03-27 21:09:12,701 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 18.81
2022-03-27 21:09:17,360 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 23.47
2022-03-27 21:09:22,059 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 28.17
2022-03-27 21:09:26,782 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 32.89
2022-03-27 21:11:01,362 [   INFO] 3304 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:11:04,103 [   INFO] 3304 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-27 21:11:04,179 [   INFO] 3304 --- lushi.py:544  : find box, try to click
2022-03-27 21:11:05,330 [   INFO] 3304 --- lushi.py:544  : find mercenaries, try to click
2022-03-27 21:11:06,432 [   INFO] 3304 --- lushi.py:544  : find team_lock, try to click
2022-03-27 21:11:07,572 [   INFO] 3304 --- lushi.py:548  : find travel, try to click
2022-03-27 21:11:09,181 [   INFO] 3304 --- lushi.py:554  : find boss list, try to click
2022-03-27 21:11:12,833 [   INFO] 3304 --- lushi.py:602  : find team_list, try to click
2022-03-27 21:11:21,375 [   INFO] 3304 --- lushi.py:253  : Start submit task...
2022-03-27 21:11:25,614 [   INFO] 3304 --- lushi.py:166  : Scanning surprise, rect: (-1, -1, 0, 0)
2022-03-27 21:11:40,490 [   INFO] 4384 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:11:43,251 [   INFO] 4384 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:11:47,820 [   INFO] 4384 --- lushi.py:896  : Last state , time taken: 5.09
2022-03-27 21:14:30,175 [   INFO] 3204 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:14:32,941 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 0.53
2022-03-27 21:14:37,333 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 4.92
2022-03-27 21:14:41,693 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 9.28
2022-03-27 21:14:46,235 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 13.83
2022-03-27 21:14:50,662 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 18.25

**Comment by zhujingpeng123** [comment]
2022-03-27 20:59:49,620 [   INFO] 2212 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 20:59:52,569 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-27 20:59:57,200 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 5.14
2022-03-27 21:00:02,097 [   INFO] 2212 --- lushi.py:896  : Last state , time taken: 10.04
2022-03-27 21:03:47,605 [   INFO] 10088 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:03:50,374 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:03:55,058 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 5.20
2022-03-27 21:03:59,768 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 9.91
2022-03-27 21:04:04,395 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 14.54
2022-03-27 21:04:09,063 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 19.21
2022-03-27 21:04:13,938 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 24.08
2022-03-27 21:04:18,543 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 28.69
2022-03-27 21:04:23,240 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 33.38
2022-03-27 21:04:28,179 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 38.32
2022-03-27 21:04:32,961 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 43.10
2022-03-27 21:04:37,539 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 47.68
2022-03-27 21:04:42,165 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 52.31
2022-03-27 21:04:47,042 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 57.18
2022-03-27 21:04:51,750 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 61.89
2022-03-27 21:04:56,557 [   INFO] 10088 --- lushi.py:896  : Last state , time taken: 66.70
2022-03-27 21:05:35,185 [   INFO] 2464 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:05:37,944 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 0.53
2022-03-27 21:05:42,684 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 5.27
2022-03-27 21:05:47,288 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 9.87
2022-03-27 21:05:51,988 [   INFO] 2464 --- lushi.py:896  : Last state , time taken: 14.57
2022-03-27 21:08:20,832 [   INFO] 5544 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:08:23,647 [   INFO] 5544 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:08:28,282 [   INFO] 5544 --- lushi.py:896  : Last state , time taken: 5.15
2022-03-27 21:08:51,641 [   INFO] 5616 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:08:54,429 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 0.54
2022-03-27 21:08:59,058 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 5.17
2022-03-27 21:09:03,609 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 9.72
2022-03-27 21:09:08,092 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 14.20
2022-03-27 21:09:12,701 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 18.81
2022-03-27 21:09:17,360 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 23.47
2022-03-27 21:09:22,059 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 28.17
2022-03-27 21:09:26,782 [   INFO] 5616 --- lushi.py:896  : Last state , time taken: 32.89
2022-03-27 21:11:01,362 [   INFO] 3304 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:11:04,103 [   INFO] 3304 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-27 21:11:04,179 [   INFO] 3304 --- lushi.py:544  : find box, try to click
2022-03-27 21:11:05,330 [   INFO] 3304 --- lushi.py:544  : find mercenaries, try to click
2022-03-27 21:11:06,432 [   INFO] 3304 --- lushi.py:544  : find team_lock, try to click
2022-03-27 21:11:07,572 [   INFO] 3304 --- lushi.py:548  : find travel, try to click
2022-03-27 21:11:09,181 [   INFO] 3304 --- lushi.py:554  : find boss list, try to click
2022-03-27 21:11:12,833 [   INFO] 3304 --- lushi.py:602  : find team_list, try to click
2022-03-27 21:11:21,375 [   INFO] 3304 --- lushi.py:253  : Start submit task...
2022-03-27 21:11:25,614 [   INFO] 3304 --- lushi.py:166  : Scanning surprise, rect: (-1, -1, 0, 0)
2022-03-27 21:11:40,490 [   INFO] 4384 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:11:43,251 [   INFO] 4384 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:11:47,820 [   INFO] 4384 --- lushi.py:896  : Last state , time taken: 5.09
2022-03-27 21:14:30,175 [   INFO] 3204 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:14:32,941 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 0.53
2022-03-27 21:14:37,333 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 4.92
2022-03-27 21:14:41,693 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 9.28
2022-03-27 21:14:46,235 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 13.83
2022-03-27 21:14:50,662 [   INFO] 3204 --- lushi.py:896  : Last state , time taken: 18.25
2022-03-27 21:23:15,369 [   INFO] 2964 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:23:18,118 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-27 21:23:22,541 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 4.94
2022-03-27 21:23:26,802 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 9.20
2022-03-27 21:23:31,190 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 13.59
2022-03-27 21:23:35,581 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 17.98
2022-03-27 21:23:39,923 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 22.32
2022-03-27 21:23:44,302 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 26.70
2022-03-27 21:23:48,660 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 31.06
2022-03-27 21:23:53,056 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 35.45
2022-03-27 21:23:57,444 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 39.84
2022-03-27 21:24:01,784 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 44.18
2022-03-27 21:24:06,143 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 48.54
2022-03-27 21:24:10,546 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 52.95
2022-03-27 21:24:14,961 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 57.36
2022-03-27 21:24:19,331 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 61.73
2022-03-27 21:24:23,810 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 66.21
2022-03-27 21:24:28,191 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 70.59
2022-03-27 21:24:32,558 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 74.96
2022-03-27 21:24:36,900 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 79.30
2022-03-27 21:24:41,638 [   INFO] 2964 --- util.py:134  : screenshot restart_block_21-24.41,312.png saved
2022-03-27 21:24:41,639 [   INFO] 2964 --- util.py:242  : try to kill hearthstone
2022-03-27 21:24:41,674 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:24:41,790 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:24:41,879 [   INFO] 2964 --- util.py:229  : Hearthstone.exe killed
2022-03-27 21:24:41,897 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:24:41,923 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:24:47,075 [   INFO] 2964 --- util.py:218  : find Battle.net.exe exists
2022-03-27 21:24:47,075 [   INFO] 2964 --- util.py:254  : Battle.net start success
2022-03-27 21:24:47,225 [   INFO] 2964 --- util.py:257  : attempt to start Hearthstone
2022-03-27 21:24:57,455 [   INFO] 2964 --- util.py:257  : attempt to start Hearthstone
2022-03-27 21:25:07,681 [   INFO] 2964 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:25:07,681 [   INFO] 2964 --- util.py:262  : Hearthstone start success
2022-03-27 21:25:12,697 [   INFO] 2964 --- util.py:265  : done
2022-03-27 21:25:12,906 [   INFO] 2964 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:25:13,405 [   INFO] 2964 --- util.py:134  : screenshot restart_unkown_21-25.13,004.png saved
2022-03-27 21:25:13,405 [   INFO] 2964 --- util.py:242  : try to kill hearthstone
2022-03-27 21:25:13,454 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:25:13,646 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:25:13,654 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:25:13,672 [   INFO] 2964 --- util.py:229  : Battle.net.exe killed
2022-03-27 21:25:13,702 [   INFO] 2964 --- util.py:229  : Hearthstone.exe killed
2022-03-27 21:25:19,006 [   INFO] 2964 --- util.py:248  : attempt to start Battle.net
2022-03-27 21:25:29,095 [   INFO] 2964 --- util.py:218  : find Battle.net.exe exists
2022-03-27 21:25:29,095 [   INFO] 2964 --- util.py:254  : Battle.net start success
2022-03-27 21:25:29,260 [   INFO] 2964 --- util.py:257  : attempt to start Hearthstone
2022-03-27 21:25:39,513 [   INFO] 2964 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:25:39,513 [   INFO] 2964 --- util.py:262  : Hearthstone start success
2022-03-27 21:25:44,520 [   INFO] 2964 --- util.py:265  : done
2022-03-27 21:25:44,694 [   INFO] 2964 --- util.py:218  : find Hearthstone.exe exists
2022-03-27 21:25:49,433 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 4.74
2022-03-27 21:25:54,187 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 9.49
2022-03-27 21:25:59,127 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 14.43
2022-03-27 21:26:03,746 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 19.05
2022-03-27 21:26:08,972 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 24.28
2022-03-27 21:26:14,304 [   INFO] 2964 --- lushi.py:896  : Last state , time taken: 29.61
