### ISSUE TITLE
以管理员权限运行run.bat文件之后还是会报psutil.AccessDenied的错误。。。

### ISSUE THREAD

**Issue by zhaoy777** [zhoubin-me/lushi_script#167]
下面是详细的log日志
2022-01-05 16:04:55,615 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:04:55,631 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=8860)
2022-01-05 16:04:55,631 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:04:55,631 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=8860)
2022-01-05 16:04:55,631 [   INFO] 9776 --- util.py:248  : attempt to start Battle.net
2022-01-05 16:05:05,737 [   INFO] 9776 --- util.py:218  : find Battle.net.exe exists
2022-01-05 16:05:05,737 [   INFO] 9776 --- util.py:254  : Battle.net start success
2022-01-05 16:05:05,746 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:05:05,748 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=8860)
2022-01-05 16:05:05,750 [   INFO] 9776 --- util.py:257  : attempt to start Hearthstone
2022-01-05 16:05:15,788 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists
2022-01-05 16:05:15,788 [   INFO] 9776 --- util.py:262  : Hearthstone start success
2022-01-05 16:05:20,791 [   INFO] 9776 --- util.py:265  : done
2022-01-05 16:05:20,797 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists
2022-01-05 16:05:23,701 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 0.5115387439727783
2022-01-05 16:05:28,786 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 5.596140146255493
2022-01-05 16:05:33,852 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 10.662047386169434
2022-01-05 16:05:39,065 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 15.875278234481812
2022-01-05 16:05:44,308 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 21.118279457092285
2022-01-05 16:05:49,622 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 26.43223214149475
2022-01-05 16:05:55,110 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 31.920576810836792
2022-01-05 16:06:00,522 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 37.33267951011658
2022-01-05 16:06:05,497 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 42.30722761154175
2022-01-05 16:06:10,584 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 47.39427733421326
2022-01-05 16:06:15,880 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 52.6901638507843
2022-01-05 16:06:21,890 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 58.70090699195862
2022-01-05 16:06:27,053 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 63.863184452056885
2022-01-05 16:06:32,379 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 69.18944883346558
2022-01-05 16:06:37,508 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 74.31841802597046
2022-01-05 16:06:43,021 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 79.83102035522461
2022-01-05 16:06:49,746 [   INFO] 9776 --- util.py:134  : screenshot restart_16-06.48,669.png saved
2022-01-05 16:06:49,747 [   INFO] 9776 --- util.py:242  : try to kill hearthstone
2022-01-05 16:06:49,755 [   INFO] 9776 --- util.py:229  : Battle.net.exe killed
2022-01-05 16:06:49,757 [   INFO] 9776 --- util.py:229  : Hearthstone.exe killed
2022-01-05 16:06:49,757 [  ERROR] 9776 --- lushi.py:821  : 错误：psutil.AccessDenied (pid=4916)
Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] 程序发出命令，但命令长度不正确。: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 816, in run
    self.run_pve()
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 851, in run_pve
    restart_game(self.lang, self.basic.bn_path)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\util.py", line 243, in restart_game
    proc_kill([bn, hs])
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\util.py", line 227, in proc_kill
    if len(p.name()) > 0 and p.name() in process_names:
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4916)
2022-01-05 16:06:49,877 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists
2022-01-05 16:06:51,883 [  ERROR] 9776 --- lushi.py:821  : 错误：No top level window found for wantedText='炉石传说', wantedClass=None, selectionFunction=None
Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 816, in run
    self.run_pve()
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 833, in run_pve
    success, loc, rect = self.check_in_screen('mercenaries')
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 110, in check_in_screen
    rect, screen = find_lushi_window(self.title)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\util.py", line 102, in find_lushi_window
    hwnd = findTopWindow(title)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\winguiauto.py", line 50, in findTopWindow
    repr(selectionFunction))
utils.winguiauto.WinGuiAutoError: No top level window found for wantedText='炉石传说', wantedClass=None, selectionFunction=None
2022-01-05 16:06:51,910 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:06:51,910 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=15524)
2022-01-05 16:06:51,910 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:06:51,926 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=15524)
2022-01-05 16:06:51,926 [   INFO] 9776 --- util.py:248  : attempt to start Battle.net
2022-01-05 16:07:01,967 [   INFO] 9776 --- util.py:218  : find Battle.net.exe exists
2022-01-05 16:07:01,968 [   INFO] 9776 --- util.py:254  : Battle.net start success
2022-01-05 16:07:01,976 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:07:01,979 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=15524)
2022-01-05 16:07:01,979 [   INFO] 9776 --- util.py:257  : attempt to start Hearthstone
2022-01-05 16:07:12,017 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:07:12,019 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists
2022-01-05 16:07:12,019 [   INFO] 9776 --- util.py:262  : Hearthstone start success
2022-01-05 16:07:17,035 [   INFO] 9776 --- util.py:265  : done
2022-01-05 16:07:17,055 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:07:17,065 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists
2022-01-05 16:07:19,742 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 0.5073838233947754
2022-01-05 16:07:24,777 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 5.54229474067688
2022-01-05 16:07:30,016 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 10.781064987182617
2022-01-05 16:07:35,246 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 16.01066303253174
2022-01-05 16:07:40,622 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 21.387205839157104
2022-01-05 16:07:46,003 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 26.76794171333313
2022-01-05 16:07:51,163 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 31.92809772491455
2022-01-05 16:07:56,442 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 37.207212686538696
2022-01-05 16:08:01,990 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 42.75519514083862
2022-01-05 16:08:07,556 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 48.32143306732178
2022-01-05 16:08:13,109 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 53.874406576156616
2022-01-05 16:08:18,408 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 59.17273306846619
2022-01-05 16:08:23,499 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 64.26355695724487
2022-01-05 16:08:28,787 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 69.55186009407043
2022-01-05 16:08:34,224 [   INFO] 9776 --- lushi.py:854  : Last state , time taken: 74.98928737640381
2022-01-05 16:08:40,061 [   INFO] 9776 --- util.py:134  : screenshot restart_16-08.39,784.png saved
2022-01-05 16:08:40,062 [   INFO] 9776 --- util.py:242  : try to kill hearthstone
2022-01-05 16:08:40,069 [   INFO] 9776 --- util.py:229  : Battle.net.exe killed
2022-01-05 16:08:40,070 [  ERROR] 9776 --- lushi.py:821  : 错误：psutil.AccessDenied (pid=4916)
Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] 程序发出命令，但命令长度不正确。: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 816, in run
    self.run_pve()
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\lushi.py", line 851, in run_pve
    restart_game(self.lang, self.basic.bn_path)
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\util.py", line 243, in restart_game
    proc_kill([bn, hs])
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\utils\util.py", line 227, in proc_kill
    if len(p.name()) > 0 and p.name() in process_names:
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\zhaoy\Desktop\script_with_python37-0.4.3\python37\Lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=4916)
2022-01-05 16:08:40,387 [   INFO] 9776 --- util.py:134  : screenshot error_16-08.40,138.png saved
2022-01-05 16:08:40,399 [   INFO] 9776 --- util.py:221  : can not get name of process psutil.AccessDenied (pid=4916)
2022-01-05 16:08:40,402 [   INFO] 9776 --- util.py:218  : find Hearthstone.exe exists

**Comment by zhaoy777** [comment]
我如果在pycharm中运行main_gui.py，不会有上述的问题了，但是会反复打开关闭炉石。。。能问一下这个是什么原因吗？
下面是对应的log日志：
2022-01-06 02:31:54,073 [   INFO] 12504 --- util.py:218  : find Battle.net.exe exists
2022-01-06 02:31:54,074 [   INFO] 12504 --- util.py:254  : Battle.net start success
2022-01-06 02:31:54,536 [   INFO] 12504 --- util.py:257  : attempt to start Hearthstone
2022-01-06 02:32:05,191 [   INFO] 12504 --- util.py:218  : find Hearthstone.exe exists
2022-01-06 02:32:05,192 [   INFO] 12504 --- util.py:262  : Hearthstone start success
2022-01-06 02:32:10,209 [   INFO] 12504 --- util.py:265  : done
2022-01-06 02:32:10,790 [   INFO] 12504 --- util.py:218  : find Hearthstone.exe exists
2022-01-06 02:32:13,883 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 0.5102288722991943
2022-01-06 02:32:19,203 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 5.830584764480591
2022-01-06 02:32:24,618 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 11.24564790725708
2022-01-06 02:32:30,283 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 16.910353660583496
2022-01-06 02:32:35,816 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 22.442957639694214
2022-01-06 02:32:42,821 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 29.44819951057434
2022-01-06 02:32:48,622 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 35.24916672706604
2022-01-06 02:32:54,440 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 41.067848205566406
2022-01-06 02:32:59,853 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 46.48014211654663
2022-01-06 02:33:05,371 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 51.99806523323059
2022-01-06 02:33:11,230 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 57.8571560382843
2022-01-06 02:33:17,204 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 63.83116960525513
2022-01-06 02:33:22,872 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 69.49900579452515
2022-01-06 02:33:28,040 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 74.66730165481567
2022-01-06 02:33:35,190 [   INFO] 12504 --- util.py:134  : screenshot restart_02-33.34,167.png saved
2022-01-06 02:33:35,192 [   INFO] 12504 --- util.py:242  : try to kill hearthstone
2022-01-06 02:33:35,597 [   INFO] 12504 --- util.py:229  : Battle.net.exe killed
2022-01-06 02:33:35,735 [   INFO] 12504 --- util.py:229  : Battle.net.exe killed
2022-01-06 02:33:35,854 [   INFO] 12504 --- util.py:229  : Hearthstone.exe killed
2022-01-06 02:33:36,003 [   INFO] 12504 --- util.py:229  : Battle.net.exe killed
2022-01-06 02:33:36,021 [   INFO] 12504 --- util.py:229  : Battle.net.exe killed
2022-01-06 02:33:42,103 [   INFO] 12504 --- util.py:248  : attempt to start Battle.net
2022-01-06 02:33:52,251 [   INFO] 12504 --- util.py:218  : find Battle.net.exe exists
2022-01-06 02:33:52,251 [   INFO] 12504 --- util.py:254  : Battle.net start success
2022-01-06 02:33:52,785 [   INFO] 12504 --- util.py:257  : attempt to start Hearthstone
2022-01-06 02:34:03,272 [   INFO] 12504 --- util.py:218  : find Hearthstone.exe exists
2022-01-06 02:34:03,273 [   INFO] 12504 --- util.py:262  : Hearthstone start success
2022-01-06 02:34:08,283 [   INFO] 12504 --- util.py:265  : done
2022-01-06 02:34:08,757 [   INFO] 12504 --- util.py:218  : find Hearthstone.exe exists
2022-01-06 02:34:14,084 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 5.326964616775513
2022-01-06 02:34:19,646 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 10.889407873153687
2022-01-06 02:34:25,309 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 16.552276134490967
2022-01-06 02:34:31,013 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 22.256535291671753
2022-01-06 02:34:36,328 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 27.571346282958984
2022-01-06 02:34:41,983 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 33.225969314575195
2022-01-06 02:34:47,141 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 38.3844211101532
2022-01-06 02:34:52,659 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 43.9016900062561
2022-01-06 02:34:58,502 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 49.74459528923035
2022-01-06 02:35:03,767 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 55.009846210479736
2022-01-06 02:35:09,684 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 60.92738318443298
2022-01-06 02:35:14,855 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 66.09853434562683
2022-01-06 02:35:20,458 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 71.70125079154968
2022-01-06 02:35:25,935 [   INFO] 12504 --- lushi.py:854  : Last state , time taken: 77.17821550369263
2022-01-06 02:35:32,440 [   INFO] 12504 --- util.py:134  : screenshot restart_02-35.31,620.png saved
2022-01-06 02:35:32,443 [   INFO] 12504 --- util.py:242  : try to kill hearthstone
2022-01-06 02:35:32,505 [   INFO] 12504 --- util.py:229  : Battle.net.exe killed
2022-01-06 02:35:32,964 [   INFO] 12504 --- util.py:229  : Hearthstone.exe killed
2022-01-06 02:35:39,574 [   INFO] 12504 --- util.py:248  : attempt to start Battle.net

**Comment by zhujingpeng123** [comment]
2022-03-26 03:19:36,779 [   INFO] 7972 --- lushi.py:896  : Last state start_game, time taken: 13.60
2022-03-26 03:19:41,861 [   INFO] 7972 --- lushi.py:896  : Last state start_game, time taken: 18.68
2022-03-26 03:19:43,851 [   INFO] 7972 --- lushi.py:740  : find member_not_ready, try to click
2022-03-26 03:19:43,949 [   INFO] 7972 --- lushi.py:350  : Start select members, battle_boss ? False start battle enemy
2022-03-26 03:19:44,227 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_032_01, hp 21, atk 6, color 2, entity_id 35
2022-03-26 03:19:44,227 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_036_01, hp 19, atk 3, color 1, entity_id 37
2022-03-26 03:19:44,227 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_035_01, hp 13, atk 4, color 4, entity_id 39
2022-03-26 03:19:45,772 [  ERROR] 7972 --- lushi.py:859  : 错误：Not possible
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 750, in state_handler
    self.select_members(self.lettuce_role_limit, battle_boss)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 430, in select_members
    raise ValueError("Not possible")
ValueError: Not possible
2022-03-26 03:19:46,614 [   INFO] 7972 --- util.py:134  : screenshot error_03-19.45,924.png saved
2022-03-26 03:19:46,619 [   INFO] 7972 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:19:49,302 [   INFO] 7972 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-26 03:19:51,244 [   INFO] 7972 --- lushi.py:740  : find member_not_ready, try to click
2022-03-26 03:19:51,342 [   INFO] 7972 --- lushi.py:350  : Start select members, battle_boss ? False start battle enemy
2022-03-26 03:19:51,624 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_032_01, hp 21, atk 6, color 2, entity_id 35
2022-03-26 03:19:51,624 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_036_01, hp 19, atk 3, color 1, entity_id 37
2022-03-26 03:19:51,625 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_035_01, hp 13, atk 4, color 4, entity_id 39
2022-03-26 03:19:53,157 [  ERROR] 7972 --- lushi.py:859  : 错误：Not possible
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 750, in state_handler
    self.select_members(self.lettuce_role_limit, battle_boss)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 430, in select_members
    raise ValueError("Not possible")
ValueError: Not possible
2022-03-26 03:19:53,914 [   INFO] 7972 --- util.py:134  : screenshot error_03-19.53,233.png saved
2022-03-26 03:19:53,920 [   INFO] 7972 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:19:56,599 [   INFO] 7972 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-26 03:19:58,539 [   INFO] 7972 --- lushi.py:740  : find member_not_ready, try to click
2022-03-26 03:19:58,622 [   INFO] 7972 --- lushi.py:350  : Start select members, battle_boss ? False start battle enemy
2022-03-26 03:19:58,905 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_032_01, hp 21, atk 6, color 2, entity_id 35
2022-03-26 03:19:58,905 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_036_01, hp 19, atk 3, color 1, entity_id 37
2022-03-26 03:19:58,906 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_035_01, hp 13, atk 4, color 4, entity_id 39
2022-03-26 03:20:00,444 [  ERROR] 7972 --- lushi.py:859  : 错误：Not possible
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 750, in state_handler
    self.select_members(self.lettuce_role_limit, battle_boss)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 430, in select_members
    raise ValueError("Not possible")
ValueError: Not possible
2022-03-26 03:20:01,217 [   INFO] 7972 --- util.py:134  : screenshot error_03-20.00,535.png saved
2022-03-26 03:20:01,223 [   INFO] 7972 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:20:03,895 [   INFO] 7972 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-26 03:20:05,856 [   INFO] 7972 --- lushi.py:740  : find member_not_ready, try to click
2022-03-26 03:20:05,960 [   INFO] 7972 --- lushi.py:350  : Start select members, battle_boss ? False start battle enemy
2022-03-26 03:20:06,236 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_032_01, hp 21, atk 6, color 2, entity_id 35
2022-03-26 03:20:06,236 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_036_01, hp 19, atk 3, color 1, entity_id 37
2022-03-26 03:20:06,236 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_035_01, hp 13, atk 4, color 4, entity_id 39
2022-03-26 03:20:07,766 [  ERROR] 7972 --- lushi.py:859  : 错误：Not possible
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 750, in state_handler
    self.select_members(self.lettuce_role_limit, battle_boss)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 430, in select_members
    raise ValueError("Not possible")
ValueError: Not possible
2022-03-26 03:20:08,549 [   INFO] 7972 --- util.py:134  : screenshot error_03-20.07,849.png saved
2022-03-26 03:20:08,554 [   INFO] 7972 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:20:11,232 [   INFO] 7972 --- lushi.py:896  : Last state , time taken: 0.51
2022-03-26 03:20:13,135 [   INFO] 7972 --- lushi.py:740  : find member_not_ready, try to click
2022-03-26 03:20:13,219 [   INFO] 7972 --- lushi.py:350  : Start select members, battle_boss ? False start battle enemy
2022-03-26 03:20:13,511 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_032_01, hp 21, atk 6, color 2, entity_id 35
2022-03-26 03:20:13,511 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_036_01, hp 19, atk 3, color 1, entity_id 37
2022-03-26 03:20:13,511 [   INFO] 7972 --- lushi.py:359  : enemy is car_id LETLT_035_01, hp 13, atk 4, color 4, entity_id 39
2022-03-26 03:20:15,022 [  ERROR] 7972 --- lushi.py:859  : 错误：Not possible
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 750, in state_handler
    self.select_members(self.lettuce_role_limit, battle_boss)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 430, in select_members
    raise ValueError("Not possible")
ValueError: Not possible
2022-03-26 03:20:15,953 [   INFO] 7972 --- util.py:134  : screenshot error_03-20.15,152.png saved
2022-03-26 03:20:15,958 [   INFO] 7972 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:22:54,245 [   INFO] 500 --- util.py:218  : find Hearthstone.exe exists
2022-03-26 03:22:57,088 [   INFO] 500 --- lushi.py:896  : Last state , time taken: 0.52
2022-03-26 03:22:58,051 [   INFO] 500 --- lushi.py:602  : find team_list, try to click
2022-03-26 03:23:06,586 [   INFO] 500 --- lushi.py:253  : Start submit task...
2022-03-26 03:23:10,772 [   INFO] 500 --- lushi.py:166  : Scanning surprise, rect: (469, 242, 2091, 1198)
2022-03-26 03:23:22,915 [   INFO] 500 --- lushi.py:192  : Found surprise during scrolling (751, 219)
2022-03-26 03:23:22,919 [   INFO] 500 --- lushi.py:631  : Surprise side right, surprise in middile False
2022-03-26 03:23:24,281 [   INFO] 500 --- lushi.py:723  : find start_game, try to click

**Comment by zhujingpeng123** [comment]
2022-03-26 06:21:40,104 [   INFO] 3948 --- lushi.py:896  : Last state , time taken: 76.97
2022-03-26 06:21:40,538 [  ERROR] 3948 --- lushi.py:859  : 错误：No top level window found for wantedText='炉石传说', wantedClass=None, selectionFunction=None
Traceback (most recent call last):
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 854, in run
    self.run_pve()
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 531, in state_handler
    success, loc, rect = self.check_in_screen(text)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\lushi.py", line 132, in check_in_screen
    rect, screen = find_lushi_window(self.title)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\utils\util.py", line 102, in find_lushi_window
    hwnd = findTopWindow(title)
  File "D:\A\lushi\script_with_python37-0.4.5 (1)\utils\winguiauto.py", line 50, in findTopWindow
    repr(selectionFunction))
utils.winguiauto.WinGuiAutoError: No top level window found for wantedText='炉石传说', wantedClass=None, selectionFunction=None
2022-03-26 06:21:40,897 [   INFO] 3948 --- util.py:218  : find Battle.net.exe exists
2022-03-26 06:21:40,897 [   INFO] 3948 --- util.py:254  : Battle.net start success
2022-03-26 06:21:41,042 [   INFO] 3948 --- util.py:257  : attempt to start Hearthstone
2022-03-26 06:25:47,932 [   INFO] 11132 --- util.py:218  : find Hearthstone.exe exists
