### ISSUE TITLE
0.4.3  刷 1-1战斗卡住了

### ISSUE THREAD

**Issue by mofengme** [zhoubin-me/lushi_script#173]
日志如下:
```
2022-02-12 13:25:12,106 [   INFO] 3872 --- lushi.py:254  : Start battle, boss ? True, scanning battlefield
2022-02-12 13:25:12,158 [  ERROR] 3872 --- lushi.py:821  : 错误：Unhandled <enum 'GameTag'>: 'LETTUCE_CURSED_ABILITY_VISUAL'
Traceback (most recent call last):
  File "D:\script_with_python37-0.4.3\lushi.py", line 816, in run
    self.run_pve()
  File "D:\script_with_python37-0.4.3\lushi.py", line 857, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "D:\script_with_python37-0.4.3\lushi.py", line 727, in state_handler
    self.start_battle(rect, battle_boss)
  File "D:\script_with_python37-0.4.3\lushi.py", line 263, in start_battle
    game = self.log_util.parse_game()
  File "D:\script_with_python37-0.4.3\utils\log_util.py", line 33, in parse_game
    self.read_log()
  File "D:\script_with_python37-0.4.3\utils\log_util.py", line 24, in read_log
    self.parser.read(f)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\parser.py", line 1100, in read
    self.read_line(line)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\parser.py", line 1135, in read_line
    return callback(self._parsing_state, ts, msg)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\parser.py", line 286, in handle_data
    tag, value = parse_initial_tag(data)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\parser.py", line 168, in parse_initial_tag
    return parse_tag(tag, value)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\utils.py", line 15, in parse_tag
    tag = parse_enum(GameTag, tag)
  File "D:\script_with_python37-0.4.3\python37\lib\site-packages\hslog\utils.py", line 10, in parse_enum
    raise Exception("Unhandled %s: %r" % (enum, value))
Exception: Unhandled <enum 'GameTag'>: 'LETTUCE_CURSED_ABILITY_VISUAL'
2022-02-12 13:25:12,861 [   INFO] 3872 --- util.py:134  : screenshot error_13-25.12,226.png saved
```
截图如下:
![error_13-25 12,226](https://user-images.githubusercontent.com/9856815/153698140-c91c6764-18b0-4d5a-870d-9d7c77551795.png)

**Comment by mofengme** [comment]
更新到 0.4.4-beta 就可以了
