### ISSUE TITLE
4月15日追加_启动脚本后，鼠标自动移到屏幕最右边点击

### ISSUE THREAD

**Issue by arrrr110** [zhoubin-me/lushi_script#182]
错误：OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'
Traceback (most recent call last):
  File "F:\Python\lushi_script\lushi.py", line 854, in run
    self.run_pve()
  File "F:\Python\lushi_script\lushi.py", line 899, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "F:\Python\lushi_script\lushi.py", line 531, in state_handler
    success, loc, rect = self.check_in_screen(text)
  File "F:\Python\lushi_script\lushi.py", line 137, in check_in_screen
    success, X, Y, conf = find_icon_location(screen, icon, self.basic.confidence)
  File "F:\Python\lushi_script\utils\util.py", line 190, in find_icon_location
    result = cv2.matchTemplate(lushi, icon, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'

------------------

我是运行了main_gui.py文件，配置好之后发现鼠标一直在往右怼，报错的问题检查了一下说是图片路径问题，但也不得要领，

谢谢你的软件，这可是一个大工程！

4月15日追问：------------------------
你好，我根据上面的错误报告，将opencv-python和opencv-contrib-python都改为：==3.4.1.15

依然会有报错：
(env) PS F:\Python\lushi_script> py .\main_gui.py
2022-04-15 15:14:19,693 [   INFO] 35104 --- util.py:218  : find Battle.net.exe exists
find Battle.net.exe exists
2022-04-15 15:14:19,695 [   INFO] 35104 --- util.py:254  : Battle.net start success
Battle.net start success
2022-04-15 15:14:19,746 [   INFO] 35104 --- util.py:257  : attempt to start Hearthstone
attempt to start Hearthstone
2022-04-15 15:14:30,015 [   INFO] 35104 --- util.py:218  : find Hearthstone.exe exists
find Hearthstone.exe exists
2022-04-15 15:14:30,029 [   INFO] 35104 --- util.py:262  : Hearthstone start success
Hearthstone start success
2022-04-15 15:14:35,045 [   INFO] 35104 --- util.py:265  : done
done
2022-04-15 15:14:35,111 [   INFO] 35104 --- util.py:218  : find Hearthstone.exe exists
find Hearthstone.exe exists
2022-04-15 15:14:37,789 [   INFO] 35104 --- lushi.py:898  : Last state , time taken: 0.51
Last state , time taken: 0.51
OpenCV(3.4.1) Error: Assertion failed (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) in cv::matchTemplate, file C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp, line 1107
2022-04-15 15:14:38,135 [  ERROR] 35104 --- lushi.py:860  : 错误：OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function cv::matchTemplate
Traceback (most recent call last):
  File "F:\Python\lushi_script\lushi.py", line 855, in run
    self.run_pve()
  File "F:\Python\lushi_script\lushi.py", line 901, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "F:\Python\lushi_script\lushi.py", line 532, in state_handler
    success, loc, rect = self.check_in_screen(text)
  File "F:\Python\lushi_script\lushi.py", line 138, in check_in_screen
    success, X, Y, conf = find_icon_location(screen, icon, self.basic.confidence)
  File "F:\Python\lushi_script\utils\util.py", line 190, in find_icon_location
    result = cv2.matchTemplate(lushi, icon, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function cv::matchTemplate

错误：OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function cv::matchTemplate
Traceback (most recent call last):
  File "F:\Python\lushi_script\lushi.py", line 855, in run
    self.run_pve()
  File "F:\Python\lushi_script\lushi.py", line 901, in run_pve
    success, tic, state, rect = self.state_handler(state, tic, state_text)
  File "F:\Python\lushi_script\lushi.py", line 532, in state_handler
    success, loc, rect = self.check_in_screen(text)
  File "F:\Python\lushi_script\lushi.py", line 138, in check_in_screen
    success, X, Y, conf = find_icon_location(screen, icon, self.basic.confidence)
  File "F:\Python\lushi_script\utils\util.py", line 190, in find_icon_location
    result = cv2.matchTemplate(lushi, icon, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(3.4.1) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function cv::matchTemplate

-----
错误的状况和上次一样：鼠标跳到屏幕的右下角，有规律的点击，但是并不能进入“佣兵战纪”，正常开展工作。

另外，版本==3.4.1.15更新了cn_install_requirements.bat后
start_gui.bat没法打开。

我不知道我是否表达清楚，感谢你的作品，期待你的答复。

**Comment by ioxv** [comment]
QQ群目前清理了一部分成员；至于报错考虑下面这几个原因：
1. 炉石运行分辨率是否是要求的分辨率（如英文1024*768，中文1600*900）
2. 运行时炉石窗口是否在前端可见
3. 尝试release的版本，看看能否正常运行。

**Comment by arrrr110** [comment]
> QQ群目前清理了一部分成员；至于报错考虑下面这几个原因：
> 1. 炉石运行分辨率是否是要求的分辨率（如英文1024*768，中文1600*900）
> 2. 运行时炉石窗口是否在前端可见
> 3. 尝试release的版本，看看能否正常运行。

谢谢，我会再次申请加入群
答1，有1600900的；
2，前端可见；
3，release版本试过一次，配置完成后成功了一次(自动点击进入"佣兵战纪")，后面就又一直失败了。

谢谢你的回复，我回头再试试

**Comment by arrrr110** [comment]
更新了最新版本，更新了安装环境，调整了分辨率后，已经可以正常运行，感谢！
