### ISSUE TITLE
填完选项发现main函数初始化失败

### ISSUE THREAD

**Issue by 519247893** [zhoubin-me/lushi_script#7]
Traceback (most recent call last):
  File "c:\Users\Desktop\python\lushi_script-main\lushi.py", line 298, in <module>
    main()
  File "c:\Users\Desktop\python\lushi_script-main\lushi.py", line 293, in main
    agent = Agent(team_id=team_id, heros_id=heros_id, skills_id=skills_id, targets_id=targets_id)
  File "c:\Users\Desktop\python\lushi_script-main\lushi.py", line 70, in __init__
    self.icons = Icons()
  File "c:\Users\Desktop\python\lushi_script-main\lushi.py", line 18, in __init__
    setattr(self, k, self.fname2img(v))
  File "c:\Users\Desktop\python\lushi_script-main\lushi.py", line 22, in fname2img
    return cv2.cvtColor(cv2.imread(fname), cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by zhoubin-me** [comment]
sorry忘更新了，你再pull一下看看
