### ISSUE TITLE
请教各位大佬 这个怎么解决 power.log是哪产生的？

### ISSUE THREAD

**Issue by war4den** [zhoubin-me/lushi_script#79]
Last state , time taken: 0.5126569271087646, side: None, surprise_in_mid: False
Traceback (most recent call last):
  File "lushi.py", line 480, in <module>
    main()
  File "lushi.py", line 476, in main
    agent.run()
  File "lushi.py", line 221, in run
    self.run_pve()
  File "lushi.py", line 312, in run_pve
    self.select_members()
  File "lushi.py", line 153, in select_members
    game = self.log_util.parse_game()
  File "D:\lushi_script-main\log_util\log_util.py", line 29, in parse_game
    self.read_log()
  File "D:\lushi_script-main\log_util\log_util.py", line 19, in read_log
    with open(os.path.join(*self.log_path), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\tx\\Hearthstone\\Logs\\Power.log'

**Comment by war4den** [comment]
炉石游戏logs里没有这个文件

**Comment by Huangyan0804** [comment]
已更新FQA，请查看
