### ISSUE TITLE
0.3.0在关底boss意外终止

### ISSUE THREAD

**Issue by Lullabyeafar** [zhoubin-me/lushi_script#85]
3人队在1-1关底boss5次复现率100%
Traceback (most recent call last):
  File "lushi.py", line 480, in <module>
    main()
  File "lushi.py", line 476, in main
    agent.run()
  File "lushi.py", line 221, in run
    self.run_pve()
  File "lushi.py", line 312, in run_pve
    self.select_members()
  File "lushi.py", line 168, in select_members
    card_id_seq = [list(game.hero_entities.values())[i].card_id for i in self.heros.battle_seq]
  File "lushi.py", line 168, in <listcomp>
    card_id_seq = [list(game.hero_entities.values())[i].card_id for i in self.heros.battle_seq]
IndexError: list index out of range

**Comment by zhoubin-me** [comment]
@Lullabyeafar 手牌多少英雄，配置文件里battle_seq 如何设置的

**Comment by Lullabyeafar** [comment]
> @Lullabyeafar 手牌多少英雄，配置文件里battle_seq 如何设置的
是我的锅 没改battle_seq 但是有些好奇为什么其他战斗不会触发

**Comment by zhoubin-me** [comment]
boss 两个人，其他三个人，你设置6个人

Lullabyeafar ***@***.***>于2021年10月31日 周日上午11:27写道：
