### ISSUE TITLE
进入战斗报错

### ISSUE THREAD

**Issue by nightlight9** [zhoubin-me/lushi_script#96]
Last state map_not_ready, time taken: 17.389389991760254, side: left, surprise_in_mid: False
Traceback (most recent call last):
  File "lushi.py", line 479, in <module>
    main()
  File "lushi.py", line 475, in main
    agent.run()
  File "lushi.py", line 220, in run
    self.run_pve()
  File "lushi.py", line 311, in run_pve
    self.select_members()
  File "lushi.py", line 156, in select_members
    game = self.log_util.parse_game()
  File "C:\lushi\lushi_script-0.3.0\log_util\log_util.py", line 29, in parse_game
    self.read_log()
  File "C:\lushi\lushi_script-0.3.0\log_util\log_util.py", line 20, in read_log
    self.parser.read(f)
  File "C:\Users\用户名\anaconda3\lib\site-packages\hslog\parser.py", line 1100, in read
    self.read_line(line)
  File "C:\Users\用户名\anaconda3\lib\site-packages\hslog\parser.py", line 1135, in read_line
    return callback(self._parsing_state, ts, msg)
  File "C:\Users\用户名\anaconda3\lib\site-packages\hslog\parser.py", line 236, in handle_game
    ps.manager.create_or_update_player(name=player_name, player_id=int(player_id))
  File "C:\Users\用户名\anaconda3\lib\site-packages\hslog\player.py", line 233, in create_or_update_player
    raise InconsistentPlayerIdError(player, player_id)
hslog.player.InconsistentPlayerIdError: (PlayerReference(name='我的战网ID', entity_id=3, player_id=2), 1)

**Comment by nightlight9** [comment]
今天进入选人界面就报这个错误，昨天正常运行

**Comment by Huangyan0804** [comment]
删除日志文件让重新生成
